/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as OrtodonciaRouteImport } from './routes/ortodoncia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSeedRouteImport } from './routes/api/seed'
import { Route as ApiPagosIndexRouteImport } from './routes/api/pagos/index'
import { Route as ApiPacientesIndexRouteImport } from './routes/api/pacientes/index'
import { Route as ApiOrtodonciaIndexRouteImport } from './routes/api/ortodoncia/index'
import { Route as ApiCitasIndexRouteImport } from './routes/api/citas/index'
import { Route as ApiPagosIdRouteImport } from './routes/api/pagos/$id'
import { Route as ApiPacientesIdRouteImport } from './routes/api/pacientes/$id'
import { Route as ApiOrtodonciaIdRouteImport } from './routes/api/ortodoncia/$id'
import { Route as ApiDashboardStatsRouteImport } from './routes/api/dashboard/stats'
import { Route as ApiCitasIdRouteImport } from './routes/api/citas/$id'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrtodonciaRoute = OrtodonciaRouteImport.update({
  id: '/ortodoncia',
  path: '/ortodoncia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagosIndexRoute = ApiPagosIndexRouteImport.update({
  id: '/api/pagos/',
  path: '/api/pagos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPacientesIndexRoute = ApiPacientesIndexRouteImport.update({
  id: '/api/pacientes/',
  path: '/api/pacientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrtodonciaIndexRoute = ApiOrtodonciaIndexRouteImport.update({
  id: '/api/ortodoncia/',
  path: '/api/ortodoncia/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCitasIndexRoute = ApiCitasIndexRouteImport.update({
  id: '/api/citas/',
  path: '/api/citas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagosIdRoute = ApiPagosIdRouteImport.update({
  id: '/api/pagos/$id',
  path: '/api/pagos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPacientesIdRoute = ApiPacientesIdRouteImport.update({
  id: '/api/pacientes/$id',
  path: '/api/pacientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrtodonciaIdRoute = ApiOrtodonciaIdRouteImport.update({
  id: '/api/ortodoncia/$id',
  path: '/api/ortodoncia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCitasIdRoute = ApiCitasIdRouteImport.update({
  id: '/api/citas/$id',
  path: '/api/citas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/facturacion': typeof FacturacionRoute
  '/login': typeof LoginRoute
  '/ortodoncia': typeof OrtodonciaRoute
  '/pacientes': typeof PacientesRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/citas/$id': typeof ApiCitasIdRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/ortodoncia/$id': typeof ApiOrtodonciaIdRoute
  '/api/pacientes/$id': typeof ApiPacientesIdRoute
  '/api/pagos/$id': typeof ApiPagosIdRoute
  '/api/citas/': typeof ApiCitasIndexRoute
  '/api/ortodoncia/': typeof ApiOrtodonciaIndexRoute
  '/api/pacientes/': typeof ApiPacientesIndexRoute
  '/api/pagos/': typeof ApiPagosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/facturacion': typeof FacturacionRoute
  '/login': typeof LoginRoute
  '/ortodoncia': typeof OrtodonciaRoute
  '/pacientes': typeof PacientesRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/citas/$id': typeof ApiCitasIdRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/ortodoncia/$id': typeof ApiOrtodonciaIdRoute
  '/api/pacientes/$id': typeof ApiPacientesIdRoute
  '/api/pagos/$id': typeof ApiPagosIdRoute
  '/api/citas': typeof ApiCitasIndexRoute
  '/api/ortodoncia': typeof ApiOrtodonciaIndexRoute
  '/api/pacientes': typeof ApiPacientesIndexRoute
  '/api/pagos': typeof ApiPagosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/facturacion': typeof FacturacionRoute
  '/login': typeof LoginRoute
  '/ortodoncia': typeof OrtodonciaRoute
  '/pacientes': typeof PacientesRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/citas/$id': typeof ApiCitasIdRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/ortodoncia/$id': typeof ApiOrtodonciaIdRoute
  '/api/pacientes/$id': typeof ApiPacientesIdRoute
  '/api/pagos/$id': typeof ApiPagosIdRoute
  '/api/citas/': typeof ApiCitasIndexRoute
  '/api/ortodoncia/': typeof ApiOrtodonciaIndexRoute
  '/api/pacientes/': typeof ApiPacientesIndexRoute
  '/api/pagos/': typeof ApiPagosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/facturacion'
    | '/login'
    | '/ortodoncia'
    | '/pacientes'
    | '/api/seed'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/citas/$id'
    | '/api/dashboard/stats'
    | '/api/ortodoncia/$id'
    | '/api/pacientes/$id'
    | '/api/pagos/$id'
    | '/api/citas/'
    | '/api/ortodoncia/'
    | '/api/pacientes/'
    | '/api/pagos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/facturacion'
    | '/login'
    | '/ortodoncia'
    | '/pacientes'
    | '/api/seed'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/citas/$id'
    | '/api/dashboard/stats'
    | '/api/ortodoncia/$id'
    | '/api/pacientes/$id'
    | '/api/pagos/$id'
    | '/api/citas'
    | '/api/ortodoncia'
    | '/api/pacientes'
    | '/api/pagos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/facturacion'
    | '/login'
    | '/ortodoncia'
    | '/pacientes'
    | '/api/seed'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/citas/$id'
    | '/api/dashboard/stats'
    | '/api/ortodoncia/$id'
    | '/api/pacientes/$id'
    | '/api/pagos/$id'
    | '/api/citas/'
    | '/api/ortodoncia/'
    | '/api/pacientes/'
    | '/api/pagos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  DashboardRoute: typeof DashboardRoute
  FacturacionRoute: typeof FacturacionRoute
  LoginRoute: typeof LoginRoute
  OrtodonciaRoute: typeof OrtodonciaRoute
  PacientesRoute: typeof PacientesRoute
  ApiSeedRoute: typeof ApiSeedRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiCitasIdRoute: typeof ApiCitasIdRoute
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiOrtodonciaIdRoute: typeof ApiOrtodonciaIdRoute
  ApiPacientesIdRoute: typeof ApiPacientesIdRoute
  ApiPagosIdRoute: typeof ApiPagosIdRoute
  ApiCitasIndexRoute: typeof ApiCitasIndexRoute
  ApiOrtodonciaIndexRoute: typeof ApiOrtodonciaIndexRoute
  ApiPacientesIndexRoute: typeof ApiPacientesIndexRoute
  ApiPagosIndexRoute: typeof ApiPagosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ortodoncia': {
      id: '/ortodoncia'
      path: '/ortodoncia'
      fullPath: '/ortodoncia'
      preLoaderRoute: typeof OrtodonciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pagos/': {
      id: '/api/pagos/'
      path: '/api/pagos'
      fullPath: '/api/pagos/'
      preLoaderRoute: typeof ApiPagosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pacientes/': {
      id: '/api/pacientes/'
      path: '/api/pacientes'
      fullPath: '/api/pacientes/'
      preLoaderRoute: typeof ApiPacientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ortodoncia/': {
      id: '/api/ortodoncia/'
      path: '/api/ortodoncia'
      fullPath: '/api/ortodoncia/'
      preLoaderRoute: typeof ApiOrtodonciaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/citas/': {
      id: '/api/citas/'
      path: '/api/citas'
      fullPath: '/api/citas/'
      preLoaderRoute: typeof ApiCitasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pagos/$id': {
      id: '/api/pagos/$id'
      path: '/api/pagos/$id'
      fullPath: '/api/pagos/$id'
      preLoaderRoute: typeof ApiPagosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pacientes/$id': {
      id: '/api/pacientes/$id'
      path: '/api/pacientes/$id'
      fullPath: '/api/pacientes/$id'
      preLoaderRoute: typeof ApiPacientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ortodoncia/$id': {
      id: '/api/ortodoncia/$id'
      path: '/api/ortodoncia/$id'
      fullPath: '/api/ortodoncia/$id'
      preLoaderRoute: typeof ApiOrtodonciaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/citas/$id': {
      id: '/api/citas/$id'
      path: '/api/citas/$id'
      fullPath: '/api/citas/$id'
      preLoaderRoute: typeof ApiCitasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  DashboardRoute: DashboardRoute,
  FacturacionRoute: FacturacionRoute,
  LoginRoute: LoginRoute,
  OrtodonciaRoute: OrtodonciaRoute,
  PacientesRoute: PacientesRoute,
  ApiSeedRoute: ApiSeedRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiCitasIdRoute: ApiCitasIdRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiOrtodonciaIdRoute: ApiOrtodonciaIdRoute,
  ApiPacientesIdRoute: ApiPacientesIdRoute,
  ApiPagosIdRoute: ApiPagosIdRoute,
  ApiCitasIndexRoute: ApiCitasIndexRoute,
  ApiOrtodonciaIndexRoute: ApiOrtodonciaIndexRoute,
  ApiPacientesIndexRoute: ApiPacientesIndexRoute,
  ApiPagosIndexRoute: ApiPagosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
